### ISSUE TITLE
search on wiki not working properly

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/digital_me#52]

**Comment by ranatrk** [comment]
I assume the problem is that some of the md file content appears in the search. I removed it to only show the page header's name for each result as shown below. Is that what is needed?

![screenshot from 2018-11-11 12-49-26](https://user-images.githubusercontent.com/17128393/48311982-9c0e7c80-e5b0-11e8-8085-e58e42cc8ef8.png)

**Comment by rkhamis** [comment]
I believe matching should be on content as well.
Let's try to make the output of the search a little more human, though
